'use strict';

const MAX_DRUPAL_VERSION = 10;
const MIN_DRUPAL_VERSION = 7;
const DEFAULT_DRUPAL_VERSION = 9;

module.exports = {
  MAX_DRUPAL_VERSION: MAX_DRUPAL_VERSION,
  MIN_DRUPAL_VERSION: MIN_DRUPAL_VERSION,
  DEFAULT_DRUPAL_VERSION: DEFAULT_DRUPAL_VERSION,
};
