'use strict';

const MAX_DRUPAL_VERSION = 9;
const MIN_DRUPAL_VERSION = 6;
const DEFAULT_DRUPAL_VERSION = 8;
const DRUPAL_DATABASE_NAME = 'drupal';

module.exports = {
  MAX_DRUPAL_VERSION: MAX_DRUPAL_VERSION,
  MIN_DRUPAL_VERSION: MIN_DRUPAL_VERSION,
  DEFAULT_DRUPAL_VERSION: DEFAULT_DRUPAL_VERSION,
  DRUPAL_DATABASE_NAME: DRUPAL_DATABASE_NAME,
};
